# Copyright 2025 The Drasi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


name: Test Drasi Learning Devcontainers
on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
  workflow_dispatch: # Allow manual triggering
  schedule:
    - cron: '0 8 * * 1' # Weekly test on Mondays


jobs:
    test-devcontainer:
      runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     tutorial:
    #       - name: "Curbside Pickup"
    #         directory: "curbside-pickup"
    #       - name: "Building Comfort"
    #         directory: "building-comfort"
    #       - name: "Fleet POC"
    #         directory: "fleet-poc"
    #       - name: "Non Events"
    #         directory: "non-events"

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            repository: drasi-project/learning

        - name: Test devcontainer build and run
          uses: devcontainers/ci@v0.3
          with:
            imageName: test-devcontainer
            subFolder: .devcontainer/curbside-pickup
            runCmd: |
                echo "🧪 Testing devcontainer build and run"
                
                # Basic checks
                echo "✅ Container is running"
                echo "Current user: $(whoami)"
                echo "Working directory: $(pwd)"
                echo "Workspace contents: $(ls -la /workspace | wc -l) items"
                
                # Run any shell scripts if they exist
                if [ -f "/workspace/.devcontainer/curbside-pickup/setup.sh" ]; then
                echo "📜 Running setup.sh"
                bash /workspace/.devcontainer/curbside-pickup/setup.sh
                fi
                
                echo "🎉 Devcontainer test completed successfully!"